### PR TITLE
ActiveDirectoryCSDsc: Enable PublishWikiContent

### LINKED ISSUE #93: AdcsTemplate documentation is missing from the Wiki
Opportunity to implement the [Publish Wiki Content](https://github.com/PowerShell/DscResource.Tests#publish-wiki-content) task?

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR enables the [Publish Wiki Content](https://github.com/PowerShell/DscResource.Tests#publish-wiki-content) opt-in deployment task for the repository.

#### This Pull Request (PR) fixes the following issues

- Fixes #93 

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/activedirectorycsdsc/95)

### CODE REVIEW

**Comment by X-Guardian** [comment]
This PR requires a GitHub Personal Access Token with repo/public_repo permissions for a user that has at least Collaborator access to the ActiveDirectoryCSDsc Module GitHub repository. This token should be encoded as an AppVeyor [secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables) and added to the `github_access_token` environment variable in the `appveyor.yml` file.

**Comment by X-Guardian** [comment]
Looks like we need to add the `WikiSource` directory as an exception to the `Common Tests - Validate Markdown Links` meta test.

**Comment by PlagueHO** [comment]
Ah right - good catch.

**Comment by X-Guardian** [comment]
To work-around the `Validate Markdown Links` meta-test failure, I've removed the hard coded links to the resources from the home.md file and made the issue link absolute rather than relative.
The links to the resources are all dynamically added to the sidebar, so don't specifically need to be on the home page.

What do you think?

**Comment by X-Guardian** [comment]
@PlagueHO, are you able to get an AppVeyor secure variable encoded Github  token for this?

**Comment by PlagueHO** [comment]
@X-Guardian - I can't encode tokens for the AppVeyor account because it runs under the PowerShell org. Once we've moved the resource kit under the DSCResource Kit org then I'll be able to.

**Comment by X-Guardian** [comment]
OK cheers @PlagueHO , any time scales on this?

I'll just park this PR for the meantime then.

**Comment by PlagueHO** [comment]
Hopefully not too far away - we're working to get the boxes ticked to start migrating these over. Need to finalize some of the details on how we'll release etc.

**Comment by PlagueHO** [comment]
Hi @X-Guardian - I'm going to close this one because it has been implemented by #111

**Pull request closed without merging**
