### PR TITLE
Updated pipeline files to support change of master to main - Fixes #124

### LINKED ISSUE #124: Rename master branch to main
As per [this statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR is the first stage of renaming the `master` branch to `main`.

#### This Pull Request (PR) fixes the following issues

- Fixes #124 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this when you get time? Should be simple one.

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-:-MPc_KF68-t6RKFo-Kt8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johlju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 267 at r1](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-MPcb6tv898T_AzzsJol:-MPcb6tw8OUPm7fUQXeE:b-qa5xd) ([raw file](https://github.com/dsccommunity/activedirectorycsdsc/blob/813ecc38446d2c619e5e566cca123e13fe361c4c/azure-pipelines.yml#L267)):*
> ```
> 'refs/heads/master'
> ```

Should this be `'refs/heads/main'`? :thinking:

**Comment by johlju** [comment]
See this: https://stackoverflow.com/questions/7541040/is-refs-heads-master-same-as-refs-remotes-origin-master-in-git

**Comment by johlju** [comment]
Running `git show-ref` does also show `refs/heads/main`.

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[azure-pipelines.yml, line 267 at r1](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-MPcb6tv898T_AzzsJol:-MPepE6E44r0HZRn0M5F:bt2xyr0) ([raw file](https://github.com/dsccommunity/activedirectorycsdsc/blob/813ecc38446d2c619e5e566cca123e13fe361c4c/azure-pipelines.yml#L267)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'refs/heads/master'
> ```

Should this be `'refs/heads/main'`? :thinking: 
</blockquote></details>

That is a really good point. I must have missed this. I think you're right. I'll need to update the blog as well. Will correct and submit new PR's to the other.

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @johlju)

___
*[azure-pipelines.yml, line 267 at r1](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-MPcb6tv898T_AzzsJol:-MPeqTX3DV0Iu9PySuw6:b-h15snn) ([raw file](https://github.com/dsccommunity/activedirectorycsdsc/blob/813ecc38446d2c619e5e566cca123e13fe361c4c/azure-pipelines.yml#L267)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

That is a really good point. I must have missed this. I think you're right. I'll need to update the blog as well. Will correct and submit new PR's to the other.
</blockquote></details>

I've fixed this now and pushed a change to the blog post. Will submit new PRs for the other repos.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-:-MPesOPq6E-kFGZIK801:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — COMMENTED** [review]
HI @johlju - fixed CodeCov.io. Can you review again?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-:-MPfXev50VkPoR8dedUJ:b-so7ztk)* status: 7 of 8 files reviewed, all discussions resolved

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-:-MPhwm1M54mZd729WCUS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.codecov.yml, line 1 at r3](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-MPhvQb_C4NIzEfba4g_:-MPhvQb_C4NIzEfba4ga:boxu3hr) ([raw file](https://github.com/dsccommunity/activedirectorycsdsc/blob/bcdcf2a76eb2cc9fde7a8dfe70ee950b72ced579/.codecov.yml#L1)):*
> ```YAML
> codecov:
> ```

Non-blocking. 

The filename should be renamed `codecov.yml`. Remove the prefix `.`. Recommendation from Codecov.io, but non-blocking for this PR.

The content is also not entirely correct, copy the content from here when you enable Codecov (add upload task to Codecov.io in azure-pipelines.yml): https://github.com/dsccommunity/ActiveDirectoryDsc/blob/master/codecov.yml

Or you can just remove this file if you don't want to upload to Codecov.io. :slightly_smiling_face:

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @johlju)

___
*[.codecov.yml, line 1 at r3](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-MPhvQb_C4NIzEfba4g_:-MPl5Ldd2HVuXTgmRDOG:b-lf6wtx) ([raw file](https://github.com/dsccommunity/activedirectorycsdsc/blob/bcdcf2a76eb2cc9fde7a8dfe70ee950b72ced579/.codecov.yml#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking. 

The filename should be renamed `codecov.yml`. Remove the prefix `.`. Recommendation from Codecov.io, but non-blocking for this PR.

The content is also not entirely correct, copy the content from here when you enable Codecov (add upload task to Codecov.io in azure-pipelines.yml): https://github.com/dsccommunity/ActiveDirectoryDsc/blob/master/codecov.yml

Or you can just remove this file if you don't want to upload to Codecov.io. :slightly_smiling_face: 
</blockquote></details>

I have fixed this anyway. Can you review again @johlju ?

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorycsdsc/125#-:-MPnHLdm4kjsrznys93g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
